-- Schema for the User and Task Management System.
-- Flyway runs this on startup; Hibernate is set to "validate" against it.

create table users (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    username   varchar(50)  not null unique,
    email      varchar(150) not null unique,
    password   varchar(100) not null,
    role       varchar(20)  not null,
    status     varchar(20)  not null,
    created_at timestamp    not null default current_timestamp
);

create table tasks (
    id               bigint generated by default as identity primary key,
    title            varchar(150) not null,
    description      varchar(2000),
    status           varchar(20)  not null,
    due_date         date,
    assigned_user_id bigint,
    created_at       timestamp    not null default current_timestamp,
    constraint fk_tasks_user foreign key (assigned_user_id) references users (id) on delete set null
);

create table comments (
    id         bigint generated by default as identity primary key,
    task_id    bigint       not null,
    user_id    bigint       not null,
    content    varchar(2000) not null,
    created_at timestamp    not null default current_timestamp,
    constraint fk_comments_task foreign key (task_id) references tasks (id) on delete cascade,
    constraint fk_comments_user foreign key (user_id) references users (id) on delete cascade
);

create table activity_logs (
    id         bigint generated by default as identity primary key,
    user_id    bigint,
    action     varchar(50)  not null,
    details    varchar(500),
    created_at timestamp    not null default current_timestamp,
    constraint fk_activity_user foreign key (user_id) references users (id) on delete set null
);
