create table notifications (
    id                bigint generated by default as identity primary key,
    recipient_user_id bigint       not null,
    type              varchar(50)  not null,
    message           varchar(500) not null,
    related_task_id   bigint,
    is_read           boolean      not null default false,
    created_at        timestamp    not null default current_timestamp,
    constraint fk_notifications_user foreign key (recipient_user_id) references users (id) on delete cascade,
    constraint fk_notifications_task foreign key (related_task_id) references tasks (id) on delete set null
);
